CREATE PROC FI_SP_IncBeneficiente
    @NOME          VARCHAR (50) ,
    @CPF           VARCHAR (11) ,
    @IDCLIENTE     BIGINT
AS
BEGIN
    INSERT INTO BENBENEFICIARIOS(NOME, CPF, IDCLIENTE) 
    VALUES (@NOME, @CPF, @IDCLIENTE)
            
    SELECT SCOPE_IDENTITY()
END